# Generated by Django 4.0.6 on 2022-07-21 13:55

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('text', ckeditor.fields.RichTextField()),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('TK', 'Tank'), ('HP', 'Healer'), ('DD', 'Damage Dealer'), ('MC', 'Merchant'), ('GM', 'Guild Master'), ('QG', 'Quest Giver'), ('SM', 'Smith'), ('LT', 'Leatherman'), ('PM', 'Potion Maker'), ('MM', 'Master Mage')], default='QG', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('text', ckeditor.fields.RichTextField()),
                ('response_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NoticeBoard.boardnotice')),
                ('response_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creation'],
            },
        ),
    ]
