# Generated by Django 4.0.6 on 2022-07-28 14:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NoticeBoard', '0004_alter_massmail_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massmail',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
